### PR TITLE
Swift 2.0 Updates

### PR DESCRIPTION
**Pull request by kylebshr**
Syntax and storyboard updates for Swift 2 and Xcode 7. Ideally, create a new swift-2.0 branch and merge this into it; that way, those on the Swift 2 beta can specify this branch in cocoapods, but master still serves the Swift 1.2 version.

### CODE REVIEW

**Comment by burczyk** [comment]
+1 for this one.

**Comment by JackoPlane** [comment]
+1

**Comment by kylebshr** [comment]
As far as I know, this should work with the GM of Swift 2 — there weren't any changes from beta 6.

**Comment by JackoPlane** [comment]
Confirmed working on Swift 2.0 GM and Xcode 7.1 beta

**Comment by kylebshr** [comment]
This is awkward — there are some commits in this PR that were for personal use and shouldn't be merged in. Is there a way to remove them from the PR?

**Comment by kylebshr** [comment]
@okmr-d — if you end up merging this in, please ignore everything in `ecae91c` and `8d17dc2`

**Pull request merged**
