### PR TITLE
Add Interface Builder support

### PR DESCRIPTION
**Pull request by chrisballinger**
* Use resource bundle for built-in podspec resources
* Add IBDesignable and IBInspectable properties
* Allow for layout with Interface Builder / NSCoding
* Refactor some common code
* Use local podspec in demo project

Cheers!

### CODE REVIEW

**Comment by chrisballinger** [comment]
Actually, scratch that, don't merge this PR. I want to tweak some more things.

**Comment by okmr-d** [comment]
That’s awesome!! Thank you so much!

**Comment by chrisballinger** [comment]
@okmr-d I might want to remove the image property I added and scoop out the UIButton currentImage instead somehow, because IB seems to have issues parsing the IBInspectables right now. Also I may want to change the imageFrame behavior because it's somewhat hard to lay out.

**Comment by okmr-d** [comment]
I'm looking forward to your PR.

**Pull request merged**
